"""
URL configuration for the social_api project.

This module defines the URL patterns for the project, including API endpoints
and documentation URLs.
"""
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from accounts.views import UserViewSet
from posts.views import PostViewSet
from comments.views import CommentViewSet
from user_messages.views import MessageViewSet
from notifications.views import NotificationViewSet
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# Define the OpenAPI schema view for API documentation.
schema_view = get_schema_view(
    openapi.Info(
        title="My API Documentation", # Title of the API documentation.
        default_version='v1', # Default API version.
        description="Detailed documentation of API endpoints", # Description of the API.
        terms_of_service="https://www.example.com/terms/", # Terms of service URL.
        contact=openapi.Contact(email="support@example.com"), # Contact email.
        license=openapi.License(name="BSD License"), # License information.
    ),
    public=True, # Make the documentation publicly accessible.
    permission_classes=[permissions.AllowAny], # Allow any user to view the documentation.
)

# Create a DefaultRouter instance to register viewsets.
router = DefaultRouter()

# Register viewsets with the router.
router.register(r'users', UserViewSet, basename='user') # Registers the UserViewSet at the /api/users/ endpoint.
router.register(r'posts', PostViewSet, basename='post') # Registers the PostViewSet at the /api/posts/ endpoint.
router.register(r'comments', CommentViewSet, basename='comment') # Registers the CommentViewSet at the /api/comments/ endpoint.
router.register(r'messages', MessageViewSet, basename='message') # Registers the MessageViewSet at the /api/messages/ endpoint.
router.register(r'notifications', NotificationViewSet, basename='notification') # Registers the NotificationViewSet at the /api/notifications/ endpoint.

# Define URL patterns for the project.
urlpatterns = [
    path('admin/', admin.site.urls), # Includes the Django admin URLs.
    path('api/', include(router.urls)), # Includes the API URLs generated by the router.
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'), # URL for the Swagger UI.
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'), # URL for the Redoc UI.
    path('swagger-json/', schema_view.without_ui(cache_timeout=0), name='schema-json'),  # URL for the raw JSON schema.
]